<?php
final class TicketsLoader {
  public static function upsertStatement(PDO $dst): PDOStatement {
    $sql = "
      INSERT INTO metabase_tickets (
        chamado, titulo_chamado, tipo_chamado,
        data_criacao, data_solucao, data_fechamento, data_ultima_atualizacao, data_id,
        status_chamado, prioridade, urgencia, impacto,
        status_sla, limite_solucao, limite_atendimento,
        sla_risco, sla_atendimento_ok, sla_solucao_ok,
        tma_minutos, mttr_minutos, aging_minutos,
        tempo_primeiro_atendimento_minutos, tempo_espera_minutos,
        servico_completo, categoria, subcategoria, servico,
        grupo_solucionador, grupo_solucionador_nome, id_grupo_solucionador,
        tipo_contrato, grupo_solucao, tipo_atividade,
        agente_solucionador, nome_solicitante, nome_tecnico_responsavel,
        entidade_cliente, localizacao_fisica,
        reaberturas, tempo_total_lancados, tem_tecnico_atribuido, tem_prioridade,
        incidente_recorrente, tags, users_id_recipient, locations_id, data_carga
      ) VALUES (
        :chamado, :titulo_chamado, :tipo_chamado,
        :data_criacao, :data_solucao, :data_fechamento, :data_ultima_atualizacao, :data_id,
        :status_chamado, :prioridade, :urgencia, :impacto,
        :status_sla, :limite_solucao, :limite_atendimento,
        :sla_risco, :sla_atendimento_ok, :sla_solucao_ok,
        :tma_minutos, :mttr_minutos, :aging_minutos,
        :tempo_primeiro_atendimento_minutos, :tempo_espera_minutos,
        :servico_completo, :categoria, :subcategoria, :servico,
        :grupo_solucionador, :grupo_solucionador_nome, :id_grupo_solucionador,
        :tipo_contrato, :grupo_solucao, :tipo_atividade,
        :agente_solucionador, :nome_solicitante, :nome_tecnico_responsavel,
        :entidade_cliente, :localizacao_fisica,
        :reaberturas, :tempo_total_lancados, :tem_tecnico_atribuido, :tem_prioridade,
        :incidente_recorrente, :tags, :users_id_recipient, :locations_id, :data_carga
      )
      ON DUPLICATE KEY UPDATE
        titulo_chamado=VALUES(titulo_chamado),
        tipo_chamado=VALUES(tipo_chamado),
        data_criacao=VALUES(data_criacao),
        data_solucao=VALUES(data_solucao),
        data_fechamento=VALUES(data_fechamento),
        data_ultima_atualizacao=VALUES(data_ultima_atualizacao),
        data_id=VALUES(data_id),
        status_chamado=VALUES(status_chamado),
        prioridade=VALUES(prioridade),
        urgencia=VALUES(urgencia),
        impacto=VALUES(impacto),
        status_sla=VALUES(status_sla),
        limite_solucao=VALUES(limite_solucao),
        limite_atendimento=VALUES(limite_atendimento),
        sla_risco=VALUES(sla_risco),
        sla_atendimento_ok=VALUES(sla_atendimento_ok),
        sla_solucao_ok=VALUES(sla_solucao_ok),
        tma_minutos=VALUES(tma_minutos),
        mttr_minutos=VALUES(mttr_minutos),
        aging_minutos=VALUES(aging_minutos),
        tempo_primeiro_atendimento_minutos=VALUES(tempo_primeiro_atendimento_minutos),
        tempo_espera_minutos=VALUES(tempo_espera_minutos),
        servico_completo=VALUES(servico_completo),
        categoria=VALUES(categoria),
        subcategoria=VALUES(subcategoria),
        servico=VALUES(servico),
        grupo_solucionador=VALUES(grupo_solucionador),
        grupo_solucionador_nome=VALUES(grupo_solucionador_nome),
        id_grupo_solucionador=VALUES(id_grupo_solucionador),
        tipo_contrato=VALUES(tipo_contrato),
        grupo_solucao=VALUES(grupo_solucao),
        tipo_atividade=VALUES(tipo_atividade),
        agente_solucionador=VALUES(agente_solucionador),
        nome_solicitante=VALUES(nome_solicitante),
        nome_tecnico_responsavel=VALUES(nome_tecnico_responsavel),
        entidade_cliente=VALUES(entidade_cliente),
        localizacao_fisica=VALUES(localizacao_fisica),
        reaberturas=VALUES(reaberturas),
        tempo_total_lancados=VALUES(tempo_total_lancados),
        tem_tecnico_atribuido=VALUES(tem_tecnico_atribuido),
        tem_prioridade=VALUES(tem_prioridade),
        incidente_recorrente=VALUES(incidente_recorrente),
        tags=VALUES(tags),
        users_id_recipient=VALUES(users_id_recipient),
        locations_id=VALUES(locations_id),
        data_carga=VALUES(data_carga)
    ";
    return $dst->prepare($sql);
  }
}